from __future__ import annotations

import json
import sys
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Dict, Tuple
from ai4test.ai4test_config import project_dir
import os

CoverageCounters = Dict[str, Dict[str, int]]  # {"instruction": {"missed": x, "covered": y}, "branch": {...}}


def parse_coverage(xml_path: str | Path) -> Tuple[
    CoverageCounters, Dict[str, CoverageCounters], Dict[str, CoverageCounters]
]:
    """Parse a JaCoCo XML file and return aggregated coverage information.

    Parameters
    ----------
    xml_path : str | Path
        Path to the XML report generated by JaCoCo.

    Returns
    -------
    global_cov : CoverageCounters
        Aggregated counters for the entire report.
    package_cov : dict[str, CoverageCounters]
        Aggregated counters for each package.
    file_cov : dict[str, CoverageCounters]
        Aggregated counters for each source file (key is full dotted path).
    """
    tree = ET.parse(xml_path)
    root = tree.getroot()

    # Helper to create a fresh counter dict
    def _blank_counter() -> CoverageCounters:
        return {
            "instruction": {"missed": 0, "covered": 0},
            "branch": {"missed": 0, "covered": 0},
        }

    global_cov = _blank_counter()
    package_cov: Dict[str, CoverageCounters] = {}
    file_cov: Dict[str, CoverageCounters] = {}

    # Global counters
    for counter in root.findall("counter"):
        ctype = counter.get("type").lower()
        if ctype in global_cov:
            global_cov[ctype]["missed"] += int(counter.get("missed"))
            global_cov[ctype]["covered"] += int(counter.get("covered"))

    # Per‑package and per‑file counters
    for package in root.findall("package"):
        pkg_name = package.get("name").replace("/", ".")
        pkg_counter = _blank_counter()

        # Source files inside the package
        for src in package.findall("sourcefile"):
            file_key = f"{pkg_name}.{src.get('name')}"
            file_counter = _blank_counter()
            for counter in src.findall("counter"):
                ctype = counter.get("type").lower()
                if ctype in file_counter:
                    missed = int(counter.get("missed"))
                    covered = int(counter.get("covered"))
                    file_counter[ctype]["missed"] += missed
                    file_counter[ctype]["covered"] += covered
                    # Add to package aggregate
                    pkg_counter[ctype]["missed"] += missed
                    pkg_counter[ctype]["covered"] += covered
            file_cov[file_key] = file_counter

        package_cov[pkg_name] = pkg_counter

    return global_cov, package_cov, file_cov


def calc_pct(covered: int, missed: int) -> float:
    """Compute coverage percentage rounded to one decimal place."""
    total = covered + missed
    return round((covered / total) * 100.0, 1) if total else 0.0


def build_diff(before_xml: str | Path, after_xml: str | Path) -> dict:
    """Return the diff JSON structure between two XML reports."""
    g_before, p_before, f_before = parse_coverage(before_xml)
    g_after, p_after, f_after = parse_coverage(after_xml)

    out = {
        "code_coverage_global": {"instruction": {}, "branch": {}},
        "code_coverage_by_package": [],
        "code_coverage_by_file": [],
        "detailed_coverage": {
            "instructions_total": g_before["instruction"]["missed"]
            + g_before["instruction"]["covered"],
            "instructions_missed_before": g_before["instruction"]["missed"],
            "instructions_missed_after": g_after["instruction"]["missed"],
            "branches_total": g_before["branch"]["missed"] + g_before["branch"]["covered"],
            "branches_missed_before": g_before["branch"]["missed"],
            "branches_missed_after": g_after["branch"]["missed"],
        },
    }

    # Global percentages & deltas
    for ctype in ("instruction", "branch"):
        before_pct = calc_pct(g_before[ctype]["covered"], g_before[ctype]["missed"])
        after_pct = calc_pct(g_after[ctype]["covered"], g_after[ctype]["missed"])
        out["code_coverage_global"][ctype] = {
            "before": before_pct,
            "after": after_pct,
            "delta_pp": round(after_pct - before_pct, 1),
        }

    # Package‑level stats
    for pkg in sorted(set(p_before) | set(p_after)):
        instr_before = calc_pct(
            p_before.get(pkg, {}).get("instruction", {}).get("covered", 0),
            p_before.get(pkg, {}).get("instruction", {}).get("missed", 0),
        )
        instr_after = calc_pct(
            p_after.get(pkg, {}).get("instruction", {}).get("covered", 0),
            p_after.get(pkg, {}).get("instruction", {}).get("missed", 0),
        )
        branch_before = calc_pct(
            p_before.get(pkg, {}).get("branch", {}).get("covered", 0),
            p_before.get(pkg, {}).get("branch", {}).get("missed", 0),
        )
        branch_after = calc_pct(
            p_after.get(pkg, {}).get("branch", {}).get("covered", 0),
            p_after.get(pkg, {}).get("branch", {}).get("missed", 0),
        )
        out["code_coverage_by_package"].append(
            {
                "package": pkg,
                "instruction": {
                    "before": instr_before,
                    "after": instr_after,
                    "delta_pp": round(instr_after - instr_before, 1),
                },
                "branch": {
                    "before": branch_before,
                    "after": branch_after,
                    "delta_pp": round(branch_after - branch_before, 1),
                },
            }
        )

    # File‑level stats (only include if coverage changed)
    for file_key in sorted(set(f_before) | set(f_after)):
        instr_before = calc_pct(
            f_before.get(file_key, {}).get("instruction", {}).get("covered", 0),
            f_before.get(file_key, {}).get("instruction", {}).get("missed", 0),
        )
        instr_after = calc_pct(
            f_after.get(file_key, {}).get("instruction", {}).get("covered", 0),
            f_after.get(file_key, {}).get("instruction", {}).get("missed", 0),
        )
        branch_before = calc_pct(
            f_before.get(file_key, {}).get("branch", {}).get("covered", 0),
            f_before.get(file_key, {}).get("branch", {}).get("missed", 0),
        )
        branch_after = calc_pct(
            f_after.get(file_key, {}).get("branch", {}).get("covered", 0),
            f_after.get(file_key, {}).get("branch", {}).get("missed", 0),
        )

        delta_instr = round(instr_after - instr_before, 1)
        delta_branch = round(branch_after - branch_before, 1)

        # Only report files where coverage actually changed
        if delta_instr != 0 or delta_branch != 0:
            out["code_coverage_by_file"].append(
                {
                    "file": file_key,
                    "instruction": {
                        "before": instr_before,
                        "after": instr_after,
                        "delta_pp": delta_instr,
                    },
                    "branch": {
                        "before": branch_before,
                        "after": branch_after,
                        "delta_pp": delta_branch,
                    },
                }
            )

    return out


def _td(value: float | str, delta: bool = False) -> str:
    """Return <td> for a table cell, optionally styling +/- deltas."""
    if delta:
        cls = "pos" if float(value) >= 0 else "neg"
        return f"<td class=\"{cls}\">{value:+}</td>"
    return f"<td>{value}</td>"


def render_html(report: dict, output_path: str | Path = "coverage_report.html") -> Path:
    """Render the diff JSON as an HTML file and return the written path."""

    # Basic inline CSS for a clean, readable report
    css = """
    body {font-family: Arial, sans-serif; margin: 2rem;}
    h1, h2 {color: #333;}
    table {border-collapse: collapse; width: 100%; margin-bottom: 2rem;}
    th, td {border: 1px solid #ddd; padding: 0.6rem; text-align: left;}
    th {background-color: #f6f6f6;}
    .pos {color: #007200; font-weight: bold;}
    .neg {color: #b30000; font-weight: bold;}
    """

    html_parts: list[str] = [
        "<html><head><meta charset=\"utf-8\"><title>JaCoCo Coverage Diff</title>",
        f"<style>{css}</style></head><body>",
        "<h1>JaCoCo Coverage Comparison</h1>",
    ]

    # Global coverage
    html_parts.append("<h2>Global Coverage</h2><table>")
    html_parts.append("<tr><th>Metric</th><th>Before (%)</th><th>After (%)</th><th>Δ&nbsp;pp</th></tr>")

    for metric in ("instruction", "branch"):
        g = report["code_coverage_global"][metric]
        html_parts.append(
            "<tr>"
            f"<td>{metric.title()}</td>"
            f"{_td(g['before'])}{_td(g['after'])}{_td(g['delta_pp'], delta=True)}"
            "</tr>"
        )
    html_parts.append("</table>")

    # Package‑level coverage
    html_parts.append("<h2>Coverage by Package</h2><table>")
    html_parts.append(
        "<tr><th>Package</th><th>Instr&nbsp;Before</th><th>Instr&nbsp;After</th><th>Instr&nbsp;Δ</th>"
        "<th>Branch&nbsp;Before</th><th>Branch&nbsp;After</th><th>Branch&nbsp;Δ</th></tr>"
    )
    for pkg in report["code_coverage_by_package"]:
        i = pkg["instruction"]
        b = pkg["branch"]
        html_parts.append(
            "<tr>"
            f"<td>{pkg['package']}</td>"
            f"{_td(i['before'])}{_td(i['after'])}{_td(i['delta_pp'], delta=True)}"
            f"{_td(b['before'])}{_td(b['after'])}{_td(b['delta_pp'], delta=True)}"
            "</tr>"
        )
    html_parts.append("</table>")

    # File‑level coverage (if any)
    if report["code_coverage_by_file"]:
        html_parts.append("<h2>Files with Coverage Changes</h2><table>")
        html_parts.append(
            "<tr><th>File</th><th>Instr&nbsp;Before</th><th>Instr&nbsp;After</th><th>Instr&nbsp;Δ</th>"
            "<th>Branch&nbsp;Before</th><th>Branch&nbsp;After</th><th>Branch&nbsp;Δ</th></tr>"
        )
        for f in report["code_coverage_by_file"]:
            i = f["instruction"]
            b = f["branch"]
            html_parts.append(
                "<tr>"
                f"<td>{f['file']}</td>"
                f"{_td(i['before'])}{_td(i['after'])}{_td(i['delta_pp'], delta=True)}"
                f"{_td(b['before'])}{_td(b['after'])}{_td(b['delta_pp'], delta=True)}"
                "</tr>"
            )
        html_parts.append("</table>")

    # Raw totals section
    det = report["detailed_coverage"]
    html_parts.append("<h2>Raw Totals</h2><ul>")
    html_parts.extend(
        [
            f"<li>Total instructions: {det['instructions_total']}</li>",
            f"<li>Instructions missed before: {det['instructions_missed_before']}</li>",
            f"<li>Instructions missed after: {det['instructions_missed_after']}</li>",
            f"<li>Total branches: {det['branches_total']}</li>",
            f"<li>Branches missed before: {det['branches_missed_before']}</li>",
            f"<li>Branches missed after: {det['branches_missed_after']}</li>",
        ]
    )
    html_parts.append("</ul></body></html>")

    # Write to disk
    output_path = Path(output_path)
    output_path.write_text("\n".join(html_parts), encoding="utf-8")
    return output_path


def main(argv: list[str] | None = None) -> None:
    argv = argv or sys.argv[1:]

    if len(argv) not in {2, 3}:
        print(
            "Usage: python coverage_diff_html.py <before.xml> <after.xml> [output.html]",
            file=sys.stderr,
        )
        sys.exit(1)

    before_xml, after_xml, *rest = argv
    output_file = rest[0] if rest else "coverage_report.html"

    print("⏳ Parsing reports and computing diff…", file=sys.stderr)
    diff = build_diff(before_xml, after_xml)

    print("📝 Rendering HTML…", file=sys.stderr)
    html_path = render_html(diff, output_file)

    print(f"✅ Coverage report written to {html_path.resolve()}")


def generate_report(pre_path, post_path, out_path):
    pre_path = os.path.join(project_dir, ".ai4framework", ".ai4test", "pre-reports", "jacoco-pre.xml")
    post_path = post_path.replace("/1/", "/final/").replace("cobertura-post-report", "coverage")
    print("⏳ Parsing reports and computing diff…", file=sys.stderr)
    diff = build_diff(pre_path, post_path)
    print("📝 Rendering HTML…", file=sys.stderr)
    html_path = render_html(diff, out_path)
    print(f"✅ Coverage report written to {html_path.resolve()}")

    out_path = Path(out_path)
    json_path = out_path.with_suffix(".json")

    # Write the diff dictionary to the JSON file
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(diff, f, indent=2)

    print(f"📝 Diff JSON written to {json_path.resolve()}")


if __name__ == "__main__":
    main()
