[DEFAULT]
config.filter=test # Packages/folders to filter files (if present in file paths, those files will be ignored). Leave empty to analyze all files.
config.rounds_count=1 # Number of times to run the process. Useful for auto patching with '--auto' option.
config.build_tool=maven # (maven, gradle, or javac)

[API]
config.provider=openai # Service to use ('groq', 'openai', 'claude')
config.key=your_api_key # Enter your API key directly
config.model=gpt-4o # Desired model name
config.temperature=0 # Desired temperature

[SAST]
config.pmd_ruleset=/app/utils/PMD-config.xml # Leave as default or change if needed

[PLUGIN]
plugin.use_diff_mode=view Diffs # Do not change
plugin.script_path=/app # Do not change