[DEFAULT]
config.filter=test # Packages/folders to filter files (if present in file paths, those files will be ignored). Leave empty to analyze all files.
config.rounds_count=1 # Number of times to run the process. Useful for auto patching with '--auto' option.
config.build_tool=maven # (maven, gradle, or javac)
config.jdk_compiler_version=6 # (4, 5, 6, 8, 11)
config.build_mode=offline # (online, offline)
config.parallel_workers=1 # Number of parallel worker processes to use during patch generation. Set to 1 for sequential execution.

[API]
config.provider=azureopenai # Service to use ('groq', 'openai', 'claude', 'azureopenai', 'deepseek')
config.key=your_api_key # Enter your API key directly
config.azure_endpoint=https://xxxxxx.azure.com/openai/deployments/xxxxxx
config.azure_api_version=2024-08-01-preview
config.model=gpt-4 # Desired model name
config.temperature=0 # Desired temperature

[SAST]
config.pmd_ruleset=/app/utils/PMD-config.xml # Leave as default or change if needed

[PLUGIN]
plugin.use_diff_mode=view Diffs # Do not change
plugin.script_path=/app # Do not change